In [1]:
#Import Library of Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [2]:
#assigning predictor and target variables
X= np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
Y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])

In [3]:
print X

[[-3  7]
 [ 1  5]
 [ 1  2]
 [-2  0]
 [ 2  3]
 [-4  0]
 [-1  1]
 [ 1  1]
 [-2  2]
 [ 2  7]
 [-4  1]
 [-2  7]]


In [4]:
print Y

[3 3 3 3 4 3 3 4 3 4 4 4]


In [5]:
#Create a Gaussian Classifier
model = GaussianNB()

In [6]:
# Train the model using the training sets 
model.fit(X, Y)

GaussianNB(priors=None)

In [7]:
#Predict Output 
predicted= model.predict([[1,2],[3,4]])
print predicted

[3 4]


In [8]:
#Predict Output 
predicted= model.predict([[1,2],[3,4], [-3,0]])
print predicted

[3 4 3]
